version: '3'
services:
  server:
    build: .
    ports:
      - '3000:3000'
    command: yarn start
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - '6379:6379'
    command: redis-server
